In [1]:
import pandas as pd

In [14]:
headers = ['e1_kb', 'rel_kb', 'rel_id', 'e2_kb', 'e1_oie', 'rel_oie', 'e2_oie',
           'e1_kb_id', 'e2_kb_id', 'e1_oie_id', 'e2_oie_id',
           'e1_oie_root', 'e2_oie_root', 'label']
data_align = pd.read_csv('../test_align_gold.tsv', sep='\t', header=None, names=headers, quoting=3)

In [15]:
data_align

,e1_kb,rel_kb,rel_id,e2_kb,e1_oie,rel_oie,e2_oie,e1_kb_id,e2_kb_id,e1_oie_id,e2_oie_id,e1_oie_root,e2_oie_root,label
0,Matilda,author,P50,Roald Dahl,Matilda,is book by,British writer Roald Dahl,Q1426188,Q25161,NaN,NaN,Matilda,British writer Roald Dahl,0
1,Odes,author,P50,Horace,Odes,are collection in,four books,Q943884,Q6197,NaN,NaN,NaN,NaN,1
2,Taxi,cast member,P161,Gisele BÃƒÂ¼ndchen,Taxi,starring,Gisele BÃƒÂ¼ndchen,Q1516852,Q152208,NaN,NaN,Taxi,Gisele BÃƒÂ¼ndchen,0
3,Casino,cast member,P161,Joe Pesci,Casino,starring,Joe Pesci,Q220910,Q20178,NaN,NaN,Casino,Joe Pesci,0
4,Nadine,cast member,P161,Kim Basinger,Nadine,starring,Kim Basinger,Q957067,Q131380,NaN,NaN,Nadine,Kim Basinger,0
5,Heroes,cast member,P161,Salman Khan,Heroes,starring,Salman Khan,Q4137388,Q9543,NaN,NaN,Heroes,Salman Khan,0
6,Shopgirl,cast member,P161,Steve Martin,Shopgirl,starring,Steve Martin,Q2005056,Q16473,NaN,NaN,Shopgirl,Steve Martin,0
7,Renegades,cast member,P161,Kiefer Sutherland,Renegades,starring,Kiefer Sutherland,Q2362846,Q103946,NaN,NaN,Renegades,Kiefer Sutherland,0
8,Rhetoric,author,P50,Aristotle,Rhetoric,is,Greek,Q1896045,Q868,NaN,NaN,NaN,NaN,1
9,Turkmenistan,capital,P36,Ashgabat,Ashgabat,named,Poltoratsk,Q874,Q23438,NaN,Q23438,NaN,Poltoratsk,1
10,Vespasian,child,P40,Titus,Vespasian,'s son is,Titus,Q1419,Q1421,NaN,NaN,Vespasian,Titus,0
11,Allentown,capital of,P1376,Lehigh County,Allentown,is,county seat of Lehigh County,Q142811,Q494117,NaN,NaN,Allentown,county seat of Lehigh County,1
12,Vaduz,capital of,P1376,Liechtenstein,Vaduz,also seat of,national parliament,Q1844,Q347,Q1844,NaN,Vaduz,NaN,1
13,Vaduz,capital of,P1376,Liechtenstein,Vaduz,is,capital,Q1844,Q347,Q1844,NaN,Vaduz,NaN,1
14,Jacob,child,P40,Dinah,Jacob,has,daughter Dinah,Q289957,Q122035,NaN,NaN,Jacob,daughter Dinah,0
15,Schopp,country,P17,Germany,Schopp,is municipality in,Germany,Q23027,Q183,NaN,NaN,Schopp,Germany,0
16,Port,country,P17,Switzerland,Port,is municipality in,canton in Switzerland located,Q68197,Q39,NaN,NaN,Port,canton in Switzerland located,0
17,Mexicali,country,P17,Mexico,Mexicali,is situated on,Mexico,Q199440,Q96,NaN,NaN,Mexicali,Mexico,0
18,Castro,country,P17,Chile,Castro,is city on,ChiloÃƒÂ© Island in Chile,Q3744,Q298,NaN,NaN,Castro,ChiloÃƒÂ© Island in Chile,0
19,Chapelle,country,P17,Switzerland,Chapelle,is municipality in,district of GlÃƒÂ¢ne in canton of Fribourg in ...,Q70175,Q39,NaN,NaN,Chapelle,district of GlÃƒÂ¢ne in canton of Fribourg in ...,0
20,Mask,cast member,P161,Cher,Mask,won,Academy Award,Q929647,Q12003,NaN,NaN,NaN,NaN,1
21,Mask,cast member,P161,Cher,Mask,is,American,Q929647,Q12003,NaN,NaN,NaN,NaN,1
22,Thursday,cast member,P161,Thomas Jane,Thursday,is,American,Q16516,Q18938,NaN,NaN,NaN,NaN,1
23,Thursday,cast member,P161,Thomas Jane,Thursday,is,1998 American crime/thriller/black comedy film...,Q16516,Q18938,NaN,NaN,NaN,NaN,1
24,McLennan,country,P17,Canada,McLennan,is town in,southwestern inland Canada,Q1857914,Q16,NaN,NaN,McLennan,southwestern inland Canada,0
25,Rosmalen,country,P17,Netherlands,Rosmalen,is town in,south of Netherlands,Q2001490,Q55,NaN,NaN,Rosmalen,south of Netherlands,0
26,Zeus,child,P40,Hercules,Zeus,taught,Hercules,Q3575329,Q534889,NaN,NaN,Zeus,Hercules,1
27,Tyrol,country,P17,Austria,Tyrol,is state in,western Austria,Q42880,Q40,NaN,NaN,Tyrol,western Austria,0
28,Tyrol,country,P17,Austria,Tyrol,is third-largest state in,Austria,Q42880,Q40,NaN,NaN,Tyrol,Austria,0
29,Inagua,country,P17,Bahamas,Inagua,is southernmost district of,Bahamas,Q1353668,Q778,NaN,NaN,Inagua,Bahamas,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,You,performer,P175,Aretha Franklin,You,is,studio album,Q1613685,Q125121,NaN,NaN,NaN,NaN,1
371,Trio,performer,P175,Dolly Parton,Trio,is,studio album,Q252401,Q180453,Q252401,NaN,Trio,NaN,1
372,Trio,performer,P175,Dolly Parton,Trio,is,first studio album,Q252401,Q180453,Q252401,NaN,Trio,NaN,1
373,Rise,performer,P175,Speed,Rise,was,album,Q6141133,Q1207328,NaN,NaN,NaN,NaN,1
374,Action,performer,P175,Sweet,Action,produced,1975 song,Q3271630,Q487919,NaN,NaN,NaN,NaN,1
375,Richard Mellon Scaife,place of birth,P19,Pittsburgh,Richard Mellon Scaife,was,billionaire,Q541074,Q1342,Q541074,NaN,Richard Mellon Scaife,NaN,1
376,Richard Mellon Scaife,place of birth,P19,Pittsburgh,Richard Mellon Scaife,owner of,Pittsburgh Tribune-Review,Q541074,Q1342,Q541074,NaN,Richard Mellon Scaife,NaN,1
377,Kenneth MacMillan,place of death,P20,London,choreographer,was director of,Royal Ballet in London,Q661555,Q84,NaN,Q84,NaN,London,1
378,Kenneth MacMillan,place of death,P20,London,Royal Ballet,is in,London,Q661555,Q84,NaN,Q84,NaN,London,1
379,Priam,place of death,P20,Troy,Priam,was,legendary king,Q170473,Q22647,Q170473,NaN,Priam,NaN,1
380,Priam,place of death,P20,Troy,Priam,was king during,Trojan War,Q170473,Q22647,Q170473,NaN,Priam,NaN,1
381,Eat,producer,P162,Andy Warhol,Eat,is,45-minute underground film created,Q386066,Q5603,NaN,NaN,NaN,NaN,1
382,Eat,producer,P162,Andy Warhol,Eat,is,underground film,Q386066,Q5603,NaN,NaN,NaN,NaN,1
383,Baseball,publisher,P123,Nintendo,Baseball,is,1983 video game,Q1041292,Q8093,NaN,NaN,NaN,NaN,1
384,Baseball,publisher,P123,Nintendo,Baseball,key to,NES 's success,Q1041292,Q8093,NaN,NaN,NaN,NaN,1
385,Greece,shares border with,P47,Turkey,Greece,however lost territory along,border to Turkey,Q41,Q43,NaN,NaN,Greece,border to Turkey,1
386,Shoreline,shares border with,P47,Seattle,Shoreline,is city in,9 miles north of Downtown Seattle,Q983657,Q5083,NaN,NaN,Shoreline,9 miles north of Downtown Seattle,1
387,Saxony,shares border with,P47,Bavaria,Saxony,is state of,Germany,Q1202,Q980,Q1202,NaN,Saxony,NaN,1
388,MLB.com,sport,P641,baseball,MLB.com,is source of,information including baseball news,Q3273050,Q5369,NaN,NaN,MLB.com,information including baseball news,1
389,New York Mets,sport,P641,baseball,Mets,are,professional,Q692417,Q5369,Q692417,NaN,Mets,NaN,1
390,shuttlecock,sport,P641,badminton,shuttlecock,is,high-drag,Q874669,Q7291,Q874669,NaN,shuttlecock,NaN,1
391,shuttlecock,sport,P641,badminton,shuttlecock,is,high-drag projectile used in sport,Q874669,Q7291,Q874669,NaN,shuttlecock,NaN,1
392,Dell Demps,sport,P641,basketball,retired American professional basketball player,president of,New Orleans Pelicans,Q1184377,Q5372,NaN,Q5372,NaN,basketball,1
393,Phoenix Suns,sport,P641,basketball,Suns,are,professional,Q164177,Q5372,Q164177,NaN,Suns,NaN,1
394,Phoenix Suns,sport,P641,basketball,Suns,are,American,Q164177,Q5372,Q164177,NaN,Suns,NaN,1
395,MLB.com,sport,P641,baseball,MLB.com,is site of,Major League Baseball,Q3273050,Q5369,Q3273050,NaN,MLB.com,NaN,1
396,MLB.com,sport,P641,baseball,users,buy tickets to,baseball games,Q3273050,Q5369,NaN,Q5369,NaN,baseball,1
397,MLB.com,sport,P641,baseball,MLB.com,allows,users,Q3273050,Q5369,Q3273050,NaN,MLB.com,NaN,1
398,MLB.com,sport,P641,baseball,MLB.com,runs,auctions,Q3273050,Q5369,Q3273050,NaN,MLB.com,NaN,1
399,Sarah,spouse,P26,Abraham,Sarah,is,In narrative wife of Abraham,Q194808,Q9181,NaN,NaN,Sarah,In narrative wife of Abraham,1

In [16]:
stats_label = data_align.groupby(['label']).size()

In [17]:
stats_label

label
0    200
1    200
dtype: int64

In [18]:
stats_triples = data_align.groupby(['e1_kb', 'rel_kb', 'e2_kb']).size()

In [19]:
stats_triples

e1_kb                 rel_kb                                            e2_kb
1941                  instance of                                       film                   1
1999                  performer                                         Prince                 1
44                    instance of                                       band                   1
ASIMO                 developer                                         Honda                  1
Aang                  spouse                                            Katara                 1
Abarat                genre                                             novel                  1
Abhishek Bachchan     spouse                                            Aishwarya Rai          1
Acklins               located in the administrative territorial entity  Bahamas                1
Action                performer                                         Sweet                  1
Africa/Brass          performer                                         John Coltrane          1
Agamemnon             father                                            Atreus                 3
Alameda               located in the administrative territorial entity  Saskatchewan           2
Alamodome             located in the administrative territorial entity  San Antonio            1
Alarm                 instance of                                       film                   1
Alex Kipchirchir      country of citizenship                            Kenya                  2
Alexander             instance of                                       city                   1
Allentown             capital of                                        Lehigh County          1
Antigone              father                                            Philip                 1
Arkansas              shares border with                                Texas                  1
BMW                   headquarters location                             Munich                 2
Baidoa                country                                           Somalia                1
Barendrecht           country                                           Netherlands            1
Baseball              publisher                                         Nintendo               2
Batucada              part of                                           samba                  1
Belmont               located in the administrative territorial entity  Nye County             1
Bergen                country                                           Netherlands            1
Bhopal                country                                           India                  2
Blackmail             instance of                                       film                   1
Bob Martinez          place of birth                                    Tampa                  1
Brandon               located in the administrative territorial entity  Rankin County          1
                                                                                              ..
Vespasian             child                                             Titus                  4
Victor                located in the administrative territorial entity  Ravalli County         2
Vittorio Gassman      languages spoken, written or signed               Italian                1
Volendam              instance of                                       village                1
Volksgarten           located in the administrative territorial entity  Vienna                 2
Wadowice              country                                           Poland                 1
Waitress              instance of                                       film                   1
Walt Disney Pictures  founded by                                        Walt Disney            2
Whisper               instance of                                       film                   1
Windsor               located in the administrative territorial entity  Indian River County    2
Wonderland            instance of                                       film                   1
Wrecked               instance of                                       film                   1
Xerxes                mother                                            Atossa                 1
You                   performer                                         Aretha Franklin        1
YouTube               founded by                                        Jawed Karim            1
Zeus                  child                                             Hercules               2
Zhengzhou             located in the administrative territorial entity  Henan                  2
Zhukovka              country                                           Russia                 1
Zwinger               instance of                                       palace                 1
anger                 instance of                                       emotion                1
benzene               has part                                          carbon                 1
biochemistry          part of                                           biology                1
diadem                subclass of                                       crown                  1
flatbread             has part                                          water                  2
grammar               part of                                           linguistics            2
pearl                 material used                                     nacre                  1
serialism             part of                                           music                  1
shuttlecock           sport                                             badminton              2
siege                 part of                                           war                    1
xXx                   director                                          Rob Cohen              2
Length: 304, dtype: int64

In [15]:
data_align[data_align.rel_id == 'P166'].groupby(['label']).size()

Series([], dtype: int64)

In [31]:
data_align = data_align[data_align.label != 1]

In [32]:
data_align

,e1_kb,rel_kb,e2_kb,e1_oie,rel_oie,e2_oie,rel_id,label,e1_oie_root,e2_oie_root,e1_desc,e2_desc
5,Schopp,country,Germany,Schopp,is municipality in,Germany,P17,0,Schopp,Germany,municipality in Germany,federal parliamentary republic in central-west...
6,Schopp,country,Germany,Schopp,is municipality in,western Germany,P17,0,Schopp,Germany,municipality in Germany,federal parliamentary republic in central-west...
7,Curtis Sittenfeld,occupation,writer,Elizabeth Curtis Sittenfeld,is,American writer,P106,0,Sittenfeld,writer,American novelist,person who uses written words to communicate i...
8,Curtis Sittenfeld,occupation,writer,Elizabeth Curtis Sittenfeld,is,writer,P106,0,Sittenfeld,writer,American novelist,person who uses written words to communicate i...
15,Dad,instance of,film,Dad,is,1989 American comedy-drama film,P31,0,Dad,film,1989 film by Gary David Goldberg,sequence of images that give the impression of...
23,Galeb,instance of,yacht,Yugoslav Navy training ship Galeb,was used as,yacht,P31,0,ship,yacht,yacht,recreational boat or ship
25,Galeb,instance of,yacht,Yugoslav Navy training ship Galeb,was used as,official yacht,P31,0,ship,yacht,yacht,recreational boat or ship
26,Acklins,located in the administrative territorial entity,Bahamas,Acklins,is island of,Bahamas,P131,0,Acklins,Bahamas,island,country in North America
32,Victor,located in the administrative territorial entity,Ravalli County,Victor,is place in,Ravalli County,P131,0,Victor,County,"census-designated place in Ravalli County, Mon...","county in Montana, United States"
33,Victor,located in the administrative territorial entity,Ravalli County,Victor,is census-designated place in,Ravalli County,P131,0,Victor,County,"census-designated place in Ravalli County, Mon...","county in Montana, United States"
49,South Australia,located in the administrative territorial entity,Australia,South Australia,Governor of,South Australia,P131,0,Australia,Australia,state of Australia,country in Oceania
56,Konstantin Melnikov,place of birth,Moscow,Konstantin Melnikov,was born in,Moscow,P19,0,Melnikov,Moscow,"Russian architect, one of the founders of cons...",capital city and the largest city of Russia; s...
58,Big,instance of,studio album,Big,is,studio album by singer released on March 21 2007,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
59,Big,instance of,studio album,Big,is,studio album released by Geffen Records,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
62,Big,instance of,studio album,Big,is,fourth studio album by American singer,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
63,Big,instance of,studio album,Big,is,fourth studio album by singer released on Marc...,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
64,Big,instance of,studio album,Big,is,studio album released on March 21 2007,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
65,Big,instance of,studio album,Big,is,fourth studio album by singer released by Geff...,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
66,Big,instance of,studio album,Big,is,fourth studio album,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
67,Big,instance of,studio album,Big,is,studio album by singer released on March 21 20...,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
68,Big,instance of,studio album,Big,is,fourth studio album released by Geffen Records,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
69,Big,instance of,studio album,Big,is,fourth studio album by singer released on Marc...,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
70,Big,instance of,studio album,Big,is,fourth studio album by American singer release...,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
71,Big,instance of,studio album,Big,is,studio album by singer,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
72,Big,instance of,studio album,Big,is,studio album by American singer,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
73,Big,instance of,studio album,Big,is,studio album,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
74,Big,instance of,studio album,Big,is,studio album by American singer released by Ge...,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
75,Big,instance of,studio album,Big,is,studio album released on March 21 2007 by Geff...,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
76,Big,instance of,studio album,Big,is,fourth studio album released on March 21 2007,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
77,Big,instance of,studio album,Big,is,fourth studio album released on March 21 2007 ...,P31,0,NaN,album,Macy Gray album,album of audio recordings made up of tracks re...
...,...,...,...,...,...,...,...,...,...,...,...,...
4738,Horst,country,Germany,Horst,is municipality in,Germany,P17,0,NaN,Germany,"municipality in the district of Steinburg, in ...",federal parliamentary republic in central-west...
4739,Calendar,instance of,film,Calendar,is,1993 drama film,P31,0,Calendar,film,1993 film by Atom Egoyan,sequence of images that give the impression of...
4740,Calendar,instance of,film,Calendar,is,1993 drama film directed by Atom Egoyan,P31,0,Calendar,film,1993 film by Atom Egoyan,sequence of images that give the impression of...
4742,Newington,located in the administrative territorial entity,London Borough of Southwark,Newington,is ward within,London Borough,P131,0,Newington,Borough,"district of Central London, England, and part ...",London borough in inner south London
4743,Newington,located in the administrative territorial entity,London Borough of Southwark,Newington,is ward within,London Borough of Southwark,P131,0,Newington,Borough,"district of Central London, England, and part ...",London borough in inner south London
4748,Octopus,instance of,album,Octopus,is,fourth album,P31,0,Octopus,album,album by British progressive rock band Gentle ...,collection of recorded music
4749,Octopus,instance of,album,Octopus,is,album,P31,0,Octopus,album,album by British progressive rock band Gentle ...,collection of recorded music
4771,Hebei,shares border with,Beijing,Hebei,surrounds,Beijing,P47,0,Hebei,Beijing,province of China,capital city of China since 1949
4773,Fashion Institute of Technology,located in the administrative territorial entity,Manhattan,Fashion Institute,is college in,Manhattan,P131,0,Institute,Manhattan,"college of art, business, design, and technolo...","borough of New York City, New York, United States"
4774,Fashion Institute of Technology,located in the administrative territorial entity,Manhattan,Fashion Institute,is public college in,Manhattan,P131,0,Institute,Manhattan,"college of art, business, design, and technolo...","borough of New York City, New York, United States"
4775,Roommates,instance of,film,Roommates,is,1995 comedy-drama film,P31,0,Roommates,film,1995 film by Peter Yates,sequence of images that give the impression of...
4776,Roommates,instance of,film,Roommates,is,1995 American comedy-drama film,P31,0,Roommates,film,1995 film by Peter Yates,sequence of images that give the impression of...
4793,Phantom,genre,musical,Phantom,is musical with,music,P136,0,Phantom,music,musical with music and lyrics by Maury Yeston ...,"work that combines songs, music, spoken dialog..."
4799,Portas,country,Spain,Portas,is municipality in,Spain,P17,0,Portas,Spain,municipality of Spain,constitutional monarchy in Southwest Europe
4800,Milkshake,performer,Kelis,Milkshake,is song by,American recording artist Kelis,P175,0,Milkshake,Kelis,2003 single by Kelis,American singer–songwriter
4801,Milkshake,performer,Kelis,Milkshake,is song by,recording artist Kelis,P175,0,Milkshake,Kelis,2003 single by Kelis,American singer–songwriter
4802,Academy of Music,located in the administrative territorial entity,Philadelphia,Academy,is in,Philadelphia,P131,0,Academy,Philadelphia,Philadelphia,"county seat city in Philadelphia County, Penns..."
4803,Academy of Music,located in the administrative territorial entity,Philadelphia,Music,home of,Opera Philadelphia,P131,0,Music,Philadelphia,Philadelphia,"county seat city in Philadelphia County, Penns..."
4804,Academy of Music,located in the administrative territorial entity,Philadelphia,Music,home of,Opera Philadelphia,P131,0,Music,Philadelphia,Philadelphia,"county seat city in Philadelphia County, Penns..."
4805,Indira Gandhi,father,Jawaharlal Nehru,Indira Gandhi,was daughter of,Jawaharlal Nehru,P22,0,Gandhi,Nehru,Indian politician and Prime Minister,"Indian lawyer, statesman, and writer, first Pr..."
4809,Radcliffe,located in the administrative territorial entity,Hardin County,Radcliffe,is city in,Hardin County,P131,0,Radcliffe,County,"city in Iowa, USA","county in Iowa, United States of America"
4810,Port Sudan,country,Sudan,Port Sudan,is city in,Sudan,P17,0,Sudan,Sudan,nejvýznamnějším súdánský přístav,republic in Africa
4811,Port Sudan,country,Sudan,Port Sudan,is city in,eastern Sudan,P17,0,Sudan,Sudan,nejvýznamnějším súdánský přístav,republic in Africa
4812,Port Sudan,country,Sudan,Port Sudan,is port city in,Sudan,P17,0,Sudan,Sudan,nejvýznamnějším súdánský přístav,republic in Africa
4813,Port Sudan,country,Sudan,Port Sudan,is port city in,eastern Sudan,P17,0,Sudan,Sudan,nejvýznamnějším súdánský přístav,republic in Africa
4818,Antigone,father,Philip,Antigone,'s father is,Philip,P22,0,Antigone,Philip,"wife of Pyrrhus I, king of Epire","Makedone, Gatte der Berenike, Heirat um 325 v...."
4821,Richmond,located in the administrative territorial entity,Dallas County,Richmond,is community in,Dallas County,P131,0,Richmond,County,"place in Alabama, United States of America","county in Alabama, United States"
4822,Richmond,located in the administrative territorial entity,Dallas County,Richmond,is unincorporated community in,Dallas County,P131,0,Richmond,County,"place in Alabama, United States of America","county in Alabama, United States"
4824,Edmonton,located in the administrative territorial entity,London Borough of Enfield,Edmonton,is area of,London Borough of Enfield,P131,0,Edmonton,Borough,"suburb of London, England","London borough in north London, England"
4825,Edmonton,located in the administrative territorial entity,London Borough of Enfield,Edmonton,is area of,London Borough,P131,0,Edmonton,Borough,"suburb of London, England","London borough in north London, England"

In [33]:
stats = data_align.groupby(['rel_kb', 'rel_oie']).size()

In [34]:
stats.to_csv('../test_align_freq.tsv', sep='\t')

### Calculate Avg Freq

In [35]:
data_stats = pd.read_csv('../test_align_freq.tsv', sep='\t', header=None, names=['rel_kb', 'rel_oie', 'freq'])

In [36]:
data_stats

,rel_kb,rel_oie,freq
0,author,are collection by,1
1,author,is book by,2
2,author,was developed by,1
3,capital,'s capital is,2
4,capital,'s city is,1
5,capital,'s settlement is,1
6,capital,also hosts,1
7,capital,be British protectorate with,1
8,capital,be protectorate with,1
9,capital,chose,1
10,capital,connects,2
11,capital,declared with,2
12,capital,hosts,1
13,capital,is,1
14,capital,is capital of,1
15,capital,is headquartered in,2
16,capital,is held in,1
17,capital,is in,2
18,capital,kilometres from,1
19,capital,of University is,1
20,capital,officially declared with,2
21,capital,was used for,1
22,capital of,Economically is city in,1
23,capital of,Economically is most prosperous city in,1
24,capital of,Economically is prosperous city in,1
25,capital of,University of,1
26,capital of,airport in,1
27,capital of,capital of,7
28,capital of,cities in,1
29,capital of,city in,1
...,...,...,...
582,subclass of,are popular uses of,1
583,subclass of,are uses of,1
584,subclass of,describes,4
585,subclass of,developments of were,16
586,subclass of,is,77
587,subclass of,is also known as,3
588,subclass of,is breed of,1
589,subclass of,is categorised as,2
590,subclass of,is comparable to,1
591,subclass of,is framed breed of,1
592,subclass of,is head of,1
593,subclass of,is in,1
594,subclass of,is known as,3
595,subclass of,is large breed of,1
596,subclass of,is large framed breed of,1
597,subclass of,often describes,4
598,subclass of,refers to,1
599,subclass of,resembling,4
600,subclass of,thus resembling,4
601,subclass of,was,16
602,taxon rank,are,23
603,taxon rank,are included along with,2
604,taxon rank,is,41
605,twinned administrative body,city behind,2
606,twinned administrative body,hottest city behind,2
607,twinned administrative body,is dubbed,2
608,twinned administrative body,is often dubbed,2
609,twinned administrative body,third city behind,2
610,twinned administrative body,third hottest city behind,2
611,work location,was founded at,1

In [37]:
data_stats_avg = data_stats.groupby(['rel_kb', 'rel_oie'], as_index=False).mean().groupby('rel_kb')['freq'].mean()

In [38]:
data_stats_avg

rel_kb
author                                               1.333333
capital                                              1.315789
capital of                                           1.266667
cast member                                          3.500000
child                                                1.200000
contains administrative territorial entity           1.666667
continent                                            1.025641
country                                              1.596330
country of citizenship                               1.909091
country of origin                                    1.636364
depicts                                              1.000000
developer                                            1.000000
director                                             4.000000
employer                                             1.250000
father                                               1.000000
followed by                                          1.000000
follows                                              1.500000
founded by                                           2.000000
genre                                               16.000000
given name                                           1.000000
has part                                             1.250000
headquarters location                                1.687500
instance of                                         21.800000
instrument                                           1.000000
languages spoken, written or signed                  2.000000
located in the administrative territorial entity     2.567901
location                                             1.000000
main subject                                         3.000000
manufacturer                                         2.500000
member of                                            2.000000
member of sports team                                1.000000
mother                                               1.000000
named after                                          1.000000
notable work                                         1.000000
occupation                                           5.000000
official language                                    1.250000
owned by                                             1.000000
parent taxon                                         1.000000
part of                                              1.125000
performer                                            4.000000
place of birth                                       2.214286
place of death                                       1.200000
position held                                        4.000000
producer                                             1.000000
residence                                            1.000000
shares border with                                   1.369565
sport                                                1.200000
sports discipline competed in                        1.000000
spouse                                               1.142857
student of                                           1.000000
subclass of                                          7.166667
taxon rank                                          22.000000
twinned administrative body                          2.000000
work location                                        1.000000
Name: freq, dtype: float64

In [39]:
data_stats_avg.to_csv('../test_align_freq_avg.tsv', sep='\t')