In [1]:
import pandas as pd
import io, json
import codecs

In [2]:
test = pd.read_csv('../test_align_gold.tsv', sep='\t', header=None, names=['e1_kb', 'rel_kb', 'rel_kb_id', 'e2_kb', 'e1_oie', 'rel_oie', 'e2_oie', 'e1_kb_id', 'e2_kb_id', 'e1_oie_id', 'e2_oie_id', 'e1_oie_root', 'e2_oie_root', 'label'], encoding='utf8')

In [3]:
test

,e1_kb,rel_kb,rel_kb_id,e2_kb,e1_oie,rel_oie,e2_oie,e1_kb_id,e2_kb_id,e1_oie_id,e2_oie_id,e1_oie_root,e2_oie_root,label
0,Matilda,author,P50,Roald Dahl,Matilda,is book by,British writer Roald Dahl,Q1426188,Q25161,NaN,NaN,Matilda,British writer Roald Dahl,0
1,Odes,author,P50,Horace,Odes,are collection in,four books,Q943884,Q6197,NaN,NaN,NaN,NaN,1
2,Taxi,cast member,P161,Gisele BÃƒÂ¼ndchen,Taxi,starring,Gisele BÃƒÂ¼ndchen,Q1516852,Q152208,NaN,NaN,Taxi,Gisele BÃƒÂ¼ndchen,0
3,Casino,cast member,P161,Joe Pesci,Casino,starring,Joe Pesci,Q220910,Q20178,NaN,NaN,Casino,Joe Pesci,0
4,Nadine,cast member,P161,Kim Basinger,Nadine,starring,Kim Basinger,Q957067,Q131380,NaN,NaN,Nadine,Kim Basinger,0
5,Heroes,cast member,P161,Salman Khan,Heroes,starring,Salman Khan,Q4137388,Q9543,NaN,NaN,Heroes,Salman Khan,0
6,Shopgirl,cast member,P161,Steve Martin,Shopgirl,starring,Steve Martin,Q2005056,Q16473,NaN,NaN,Shopgirl,Steve Martin,0
7,Renegades,cast member,P161,Kiefer Sutherland,Renegades,starring,Kiefer Sutherland,Q2362846,Q103946,NaN,NaN,Renegades,Kiefer Sutherland,0
8,Rhetoric,author,P50,Aristotle,Rhetoric,is,Greek,Q1896045,Q868,NaN,NaN,NaN,NaN,1
9,Turkmenistan,capital,P36,Ashgabat,Ashgabat,named,Poltoratsk,Q874,Q23438,NaN,Q23438,NaN,Poltoratsk,1
10,Vespasian,child,P40,Titus,Vespasian,'s son is,Titus,Q1419,Q1421,NaN,NaN,Vespasian,Titus,0
11,Allentown,capital of,P1376,Lehigh County,Allentown,is,county seat of Lehigh County,Q142811,Q494117,NaN,NaN,Allentown,county seat of Lehigh County,1
12,Vaduz,capital of,P1376,Liechtenstein,Vaduz,also seat of,national parliament,Q1844,Q347,Q1844,NaN,Vaduz,NaN,1
13,Vaduz,capital of,P1376,Liechtenstein,Vaduz,is,capital,Q1844,Q347,Q1844,NaN,Vaduz,NaN,1
14,Jacob,child,P40,Dinah,Jacob,has,daughter Dinah,Q289957,Q122035,NaN,NaN,Jacob,daughter Dinah,0
15,Schopp,country,P17,Germany,Schopp,is municipality in,Germany,Q23027,Q183,NaN,NaN,Schopp,Germany,0
16,Port,country,P17,Switzerland,Port,is municipality in,canton in Switzerland located,Q68197,Q39,NaN,NaN,Port,canton in Switzerland located,0
17,Mexicali,country,P17,Mexico,Mexicali,is situated on,Mexico,Q199440,Q96,NaN,NaN,Mexicali,Mexico,0
18,Castro,country,P17,Chile,Castro,is city on,ChiloÃƒÂ© Island in Chile,Q3744,Q298,NaN,NaN,Castro,ChiloÃƒÂ© Island in Chile,0
19,Chapelle,country,P17,Switzerland,Chapelle,is municipality in,district of GlÃƒÂ¢ne in canton of Fribourg in ...,Q70175,Q39,NaN,NaN,Chapelle,district of GlÃƒÂ¢ne in canton of Fribourg in ...,0
20,Mask,cast member,P161,Cher,Mask,won,Academy Award,Q929647,Q12003,NaN,NaN,NaN,NaN,1
21,Mask,cast member,P161,Cher,Mask,is,American,Q929647,Q12003,NaN,NaN,NaN,NaN,1
22,Thursday,cast member,P161,Thomas Jane,Thursday,is,American,Q16516,Q18938,NaN,NaN,NaN,NaN,1
23,Thursday,cast member,P161,Thomas Jane,Thursday,is,1998 American crime/thriller/black comedy film...,Q16516,Q18938,NaN,NaN,NaN,NaN,1
24,McLennan,country,P17,Canada,McLennan,is town in,southwestern inland Canada,Q1857914,Q16,NaN,NaN,McLennan,southwestern inland Canada,0
25,Rosmalen,country,P17,Netherlands,Rosmalen,is town in,south of Netherlands,Q2001490,Q55,NaN,NaN,Rosmalen,south of Netherlands,0
26,Zeus,child,P40,Hercules,Zeus,taught,Hercules,Q3575329,Q534889,NaN,NaN,Zeus,Hercules,1
27,Tyrol,country,P17,Austria,Tyrol,is state in,western Austria,Q42880,Q40,NaN,NaN,Tyrol,western Austria,0
28,Tyrol,country,P17,Austria,Tyrol,is third-largest state in,Austria,Q42880,Q40,NaN,NaN,Tyrol,Austria,0
29,Inagua,country,P17,Bahamas,Inagua,is southernmost district of,Bahamas,Q1353668,Q778,NaN,NaN,Inagua,Bahamas,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,You,performer,P175,Aretha Franklin,You,is,studio album,Q1613685,Q125121,NaN,NaN,NaN,NaN,1
371,Trio,performer,P175,Dolly Parton,Trio,is,studio album,Q252401,Q180453,Q252401,NaN,Trio,NaN,1
372,Trio,performer,P175,Dolly Parton,Trio,is,first studio album,Q252401,Q180453,Q252401,NaN,Trio,NaN,1
373,Rise,performer,P175,Speed,Rise,was,album,Q6141133,Q1207328,NaN,NaN,NaN,NaN,1
374,Action,performer,P175,Sweet,Action,produced,1975 song,Q3271630,Q487919,NaN,NaN,NaN,NaN,1
375,Richard Mellon Scaife,place of birth,P19,Pittsburgh,Richard Mellon Scaife,was,billionaire,Q541074,Q1342,Q541074,NaN,Richard Mellon Scaife,NaN,1
376,Richard Mellon Scaife,place of birth,P19,Pittsburgh,Richard Mellon Scaife,owner of,Pittsburgh Tribune-Review,Q541074,Q1342,Q541074,NaN,Richard Mellon Scaife,NaN,1
377,Kenneth MacMillan,place of death,P20,London,choreographer,was director of,Royal Ballet in London,Q661555,Q84,NaN,Q84,NaN,London,1
378,Kenneth MacMillan,place of death,P20,London,Royal Ballet,is in,London,Q661555,Q84,NaN,Q84,NaN,London,1
379,Priam,place of death,P20,Troy,Priam,was,legendary king,Q170473,Q22647,Q170473,NaN,Priam,NaN,1
380,Priam,place of death,P20,Troy,Priam,was king during,Trojan War,Q170473,Q22647,Q170473,NaN,Priam,NaN,1
381,Eat,producer,P162,Andy Warhol,Eat,is,45-minute underground film created,Q386066,Q5603,NaN,NaN,NaN,NaN,1
382,Eat,producer,P162,Andy Warhol,Eat,is,underground film,Q386066,Q5603,NaN,NaN,NaN,NaN,1
383,Baseball,publisher,P123,Nintendo,Baseball,is,1983 video game,Q1041292,Q8093,NaN,NaN,NaN,NaN,1
384,Baseball,publisher,P123,Nintendo,Baseball,key to,NES 's success,Q1041292,Q8093,NaN,NaN,NaN,NaN,1
385,Greece,shares border with,P47,Turkey,Greece,however lost territory along,border to Turkey,Q41,Q43,NaN,NaN,Greece,border to Turkey,1
386,Shoreline,shares border with,P47,Seattle,Shoreline,is city in,9 miles north of Downtown Seattle,Q983657,Q5083,NaN,NaN,Shoreline,9 miles north of Downtown Seattle,1
387,Saxony,shares border with,P47,Bavaria,Saxony,is state of,Germany,Q1202,Q980,Q1202,NaN,Saxony,NaN,1
388,MLB.com,sport,P641,baseball,MLB.com,is source of,information including baseball news,Q3273050,Q5369,NaN,NaN,MLB.com,information including baseball news,1
389,New York Mets,sport,P641,baseball,Mets,are,professional,Q692417,Q5369,Q692417,NaN,Mets,NaN,1
390,shuttlecock,sport,P641,badminton,shuttlecock,is,high-drag,Q874669,Q7291,Q874669,NaN,shuttlecock,NaN,1
391,shuttlecock,sport,P641,badminton,shuttlecock,is,high-drag projectile used in sport,Q874669,Q7291,Q874669,NaN,shuttlecock,NaN,1
392,Dell Demps,sport,P641,basketball,retired American professional basketball player,president of,New Orleans Pelicans,Q1184377,Q5372,NaN,Q5372,NaN,basketball,1
393,Phoenix Suns,sport,P641,basketball,Suns,are,professional,Q164177,Q5372,Q164177,NaN,Suns,NaN,1
394,Phoenix Suns,sport,P641,basketball,Suns,are,American,Q164177,Q5372,Q164177,NaN,Suns,NaN,1
395,MLB.com,sport,P641,baseball,MLB.com,is site of,Major League Baseball,Q3273050,Q5369,Q3273050,NaN,MLB.com,NaN,1
396,MLB.com,sport,P641,baseball,users,buy tickets to,baseball games,Q3273050,Q5369,NaN,Q5369,NaN,baseball,1
397,MLB.com,sport,P641,baseball,MLB.com,allows,users,Q3273050,Q5369,Q3273050,NaN,MLB.com,NaN,1
398,MLB.com,sport,P641,baseball,MLB.com,runs,auctions,Q3273050,Q5369,Q3273050,NaN,MLB.com,NaN,1
399,Sarah,spouse,P26,Abraham,Sarah,is,In narrative wife of Abraham,Q194808,Q9181,NaN,NaN,Sarah,In narrative wife of Abraham,1

In [10]:
triples = []
for i in range(len(test)):
    e1_oie = test['e1_oie'][i].encode('ascii', 'ignore').decode('ascii')
    rel_oie = test['rel_oie'][i].encode('ascii', 'ignore').decode('ascii')
    e2_oie = test['e2_oie'][i].encode('ascii', 'ignore').decode('ascii')
    item_oie = {
        "_id": i,
        "triple": [
            e1_oie,
            rel_oie,
            e2_oie
        ],
        "triple_norm": [
            e1_oie.lower(),
            rel_oie.lower(),
            e2_oie.lower()
        ],
        "true_link": {
            "subject": test['e1_kb_id'][i],
            "object":  test['e2_kb_id'][i]
        },
        "src_sentences": [
            e1_oie + ' ' + rel_oie + ' ' + e2_oie
        ],
        "entity_linking": {
            "subject":  test['e1_kb'][i],
            "object":   test['e2_kb'][i]
        },
        "kbp_info": []
    }
    
    e1_kb = test['e1_kb'][i].encode('ascii', 'ignore').decode('ascii')
    rel_kb = test['rel_kb'][i].encode('ascii', 'ignore').decode('ascii')
    e2_kb = test['e2_kb'][i].encode('ascii', 'ignore').decode('ascii')
    item_kb = {
        "_id": i,
        "triple": [
            e1_kb,
            rel_kb,
            e2_kb
        ],
        "triple_norm": [
            e1_kb.lower(),
            rel_kb.lower(),
            e2_kb.lower()
        ],
        "true_link": {
            "subject": test['e1_kb_id'][i],
            "object":  test['e2_kb_id'][i]
        },
        "src_sentences": [
            e1_kb + ' ' + rel_kb + ' ' + e2_kb
        ],
        "entity_linking": {
            "subject":  test['e1_kb'][i],
            "object":   test['e2_kb'][i]
        },
        "kbp_info": []
    }
    triples.append(item_kb)
    triples.append(item_oie)

In [11]:
with codecs.open('../../../cesi/data/reverb45k/reverb45k_test', 'w', encoding='utf-8') as f:
    for item in triples:
        f.write(json.dumps(item, ensure_ascii=False))
        f.write('\n')